version: 0.0.1.{build}
platform: x64
image: Visual Studio 2017

clone_folder: C:\projects\dirbis

clone_depth: 1

init:
  - git config --global core.autocrlf true

install:
  - choco install dmd
  - choco install dub
  - C:\D\dmd2\windows\bin\dub.exe --version

build_script:
  - cd C:\projects\dirbis
  - C:\D\dmd2\windows\bin\dub.exe

test: off

artifacts:
  - path: irbis.exe
    name: irbis
